[김주현] Add : 상품데이터조회 기능구현 및 유닛테스트 완료
wecode-bootcamp-korea/25-2nd-NoSleepPlace-backend pull request #3
Opened 2021-10-21 18:46 UTC by kjhabc2002

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메뉴 및 카테고리별로 상품을 조회할 수 있는 기능구현
- 상세페이지에 대한 상품정보를 조회할 수 있는 기능구현
- 기능구현 완료 후 유닛테스트를 통해 사후 버그 미리 방지

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- PlaceListView에서 url데이터를 가져오고 싶어서 역참조 image_set을 이용해보았습니다.  이번에 역참조에 대해 공부해보니까 역참조 방식이 두가지가 있다는 것을 알게 되었는데, related_name을 사용하는 것과 _set을 사용하는 것 중에 어느방식이 더 효율적인지 궁금합니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 이번에 유닛테스트를 처음 사용해보았는데, 계속해서 버그발생한 부분들을 고쳐나가는 과정이 재밌었...스읍니다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-10-21 19:49 UTC, kjhabc2002 commented
- 상품전체조회 통신테스트
![스크린샷, 2021-10-22 04-46-53](https://user-images.githubusercontent.com/41711271/138346683-3c750453-ae50-4f01-bf38-628e6c12658a.png)

- 메뉴별 상품조회 통신테스트
![스크린샷, 2021-10-22 03-07-41](https://user-images.githubusercontent.com/41711271/138347165-f3fe61a8-8eb9-4e72-9914-15b02d9acf99.png)

- 카테고리별 상품조회 통신테스트
![스크린샷, 2021-10-22 03-07-15](https://user-images.githubusercontent.com/41711271/138346175-7fbc0d13-1253-46bd-b713-42d1a5422158.png)

- 상세페이지 상품정보조회 통신테스트
![스크린샷, 2021-10-22 03-06-52](https://user-images.githubusercontent.com/41711271/138346457-77ccb58b-74bd-4358-8a86-933271ef3001.png)

- 유닛테스트 결과
![스크린샷, 2021-10-22 04-49-04](https://user-images.githubusercontent.com/41711271/138346938-40c7cd79-f974-4a8e-8c63-970bb0624c2c.png)

2021-10-22 02:11 UTC, lordmyshepherd requested changes

2021-10-22 02:11 UTC, lordmyshepherd commented on books/models.py
> +
이미 merge된 코드가 또 올라왔네요? 확인하고 지워주세요!

2021-10-22 02:11 UTC, lordmyshepherd commented on core/models.py
> +class TimeStampedModel(models.Model) :
해당 파일도 마찬가지입니다.
이미 merge된 코드가 또 올라왔네요? 확인하고 지워주세요!

2021-10-22 02:11 UTC, lordmyshepherd commented on places/models.py
> +class Menu(TimeStampedModel):
해당 파일도 마찬가지입니다.
이미 merge된 코드가 또 올라왔네요? 확인하고 지워주세요!

2021-10-22 02:11 UTC, lordmyshepherd commented on places/views.py
> +from places.models        import Place
1. 사용하지 않는 모듈은 지워주세요.
2. import 문 컨벤션 확인해서 맞춰주세요!
```suggestion
import json

from django.http.response import HttpResponse, JsonResponse
from django.views         import View

from places.models        import Place
```

2021-10-22 02:11 UTC, lordmyshepherd commented on users/models.py
> +    kakao_id      = models.CharField(max_length=50, unique=True)
이미 merge된 코드가 또 올라왔네요? 확인하고 지워주세요!

2021-10-22 02:11 UTC, lordmyshepherd commented on places/views.py
> +                places = Place.objects.all()
None은 Falsy한 값입니다.
그러므로 if None: <- False가 됩니다. 그러므로 `if category:`만으로 충분합니다.
```python
(X) if category and category !=None:

(O) if category:
```

2021-10-22 02:11 UTC, lordmyshepherd commented on places/views.py
> +                places = Place.objects.all()
추가로 if 문이 너무 많네요! 
if문이 많아지면 가독성 뿐만 아니라 로직이 갈라지게 됩니다. 로직이 갈라지게 되면 나중에 해당 함수에 버그가 발생해서 디버깅할 때 여러 경우를 따져봐야 합니다.

그러므로 if문의 사용을 최대한 줄여서 로직이 분기적으로가 아니라 선형적으로 작성될 수 있도록 해주시는게 좋습니다.
(구조적으로 프로그래밍 한다고 볼 수 있습니다.)

**if문을 사용하지 않고 dictionary를 활용해서 구현해보세요!**

2021-10-22 02:11 UTC, lordmyshepherd commented on places/views.py
> +class PlaceDetailView(View):
나머지는 restful하게 정말 잘 만들어 주셨습니다~

2021-10-22 08:35 UTC, kjhabc2002 commented on places/views.py
> +                places = Place.objects.all()
저번 프로젝트에서 사용했던 상품필터링 관련한 dictionary문법을 적용해보려고 하였으나 상품정렬과는 다른용도라서 로직을 구현하기가 힘들었습니다. 
결국엔 멘토분께 도움을 요청드려서 해결하였습니다.
dictionary comprehension 문법으로 적용하고나니 코드가독성이 좋아졌지만..저에겐 어려운 고급스킬이라서 더 간단한 문법으로 해결가능한건지 궁금합니다.

2021-10-25 01:43 UTC, lordmyshepherd commented on places/views.py
> +                places = Place.objects.all()
잘 구현해 주셨습니다. 더 좋은 코드 더 좋은 구조라고 하면 어렵다고 하더라도 방법을 익히고 내것으로 만드는게 중요합니다.
지금 당장은 이해가 가지 않더라도 이 구조를 이해하려고 노력하고 사용해 주세요!

2021-10-25 01:47 UTC, lordmyshepherd requested changes

2021-10-25 01:47 UTC, lordmyshepherd commented on places/views.py
> +            filter_set = {filter_prefixes.get(key) : value[0] for (key, value) in dict(request.GET).items()}
value[0]을 붙이는 이유가 뭔가요??

```suggestion
            filter_set = {filter_prefixes.get(key) : value for (key, value) in dict(request.GET).items()}
```

2021-10-25 04:22 UTC, kjhabc2002 commented on places/views.py
> +            filter_set = {filter_prefixes.get(key) : value[0] for (key, value) in dict(request.GET).items()}
result결과값이 배열형태라서 uri를 category=1로 요청하였을때 응답으로 category_id에 대한 키값을 ['1']와 같이 배열에 담아서 보내게 되어 데이터를 못읽어옵니다. 그래서 value[0]을 주게되면 키값을 1로 받아오게 되므로 정상적으로 데이터가 나옵니다. 
사실 승현멘토분께서 풀어주신거라 제가 이해한 부분이 맞는지....모르겠습니다ㅠ

2021-10-25 07:40 UTC, lordmyshepherd commented on places/views.py
> +            filter_set = {filter_prefixes.get(key) : value[0] for (key, value) in dict(request.GET).items()}
주현님! client에서 요청 보내는 형태가 `:8000?category=[1,2]`와 같은 방식으로 배열에 담아서 보내주고 있나요?

2021-10-25 09:09 UTC, kjhabc2002 commented on places/views.py
> +            filter_set = {filter_prefixes.get(key) : value[0] for (key, value) in dict(request.GET).items()}
네네 category=[1] 형태로 담아서 보내주기 때문에 value[0]으로 해야 category=1으로 보내주게 됩니다.

2021-10-25 12:17 UTC, lordmyshepherd requested changes

2021-10-25 12:17 UTC, lordmyshepherd commented on places/views.py
> +            filter_set = {filter_prefixes.get(key) : value[0] for (key, value) in dict(request.GET).items()}
그렇다면 아래와 같이 __in을 사용하시면 될 것 같습니다.
```python
            filter_prefixes = {
                'menu'     : 'category__menu_id',
                'category' : 'category_id__in'
            }

filter_set = {filter_prefixes.get(key) : value for (key, value) in dict(request.GET).items()}
```

2021-10-25 16:05 UTC, kjhabc2002 commented
네 알려주신대로 __in을 사용해보니 리스트에 있는 값을 읽어와서 앞서 사용했던 방법과 동일하게 정상출력됩니다. 앞으로 queryset api문서를 잘 활용해야겠다는 생각이 들었습니다.

2021-10-26 01:22 UTC, lordmyshepherd commented
LGTM 👍

2021-10-26 01:22 UTC, merged